### ISSUE TITLE
migrate to null-safety

### ISSUE THREAD

**Issue by ghost** [aeri/Noesys#1]
HI @aeri ,

Hope you are all well !

I was wondering if it would possible to migrate the projet to null-safety ?

Cheers,
Luc

**Comment by aeri** [comment]
Hi @lucmichalski,

Thanks for the suggestion and the truth is that I would like to put more time to this project to improve and maintain it, I think it's a good idea, I have already worked with sound null safety but never in Flutter, I will keep an eye on it and we can implement it.

Of course, feel free to modify anything and make a PR to raise the project.

Best regards.
Naval.
